### ISSUE TITLE
Unable to place Microphone Bug on the ground

### ISSUE THREAD

**Issue by brennan-ennis** [InZidiuZ/op-framework-issue-tracker#1502]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/designatio/

**Summary:**
Write a short summary of what you are experiencing.
I am attempting to place the microphone bug on the ground/wall/object and I am unable. I use the microphone bug and I go through the animation, but no progress bar shows up and I am unable to install the bug. I am able to place the microphone bug inside a car or on a person, but not on the ground or wall etc.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Buy a microphone bug and attempt to use it anywhere except inside or near a vehicle or person.

**Expected Results:**
What are the expected results?
The progress bar should show me the progress on installing the bug and the bug should then be placed and be able to be used.

**Actual Results:**
What are the actual results?
No progress bar shows up and the bug is not installed.

## Additional Information

**Server:**
What server/community did this issue occur in?
NA/EU server.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This should be resolved with version 3269.

**Comment by brennan-ennis** [comment]
As of testing it right now, I still cannot place the microphone bug on the ground. A new issue that I don't think happened last patch, I cannot open the ESC menu after attempting to place a microphone bug on the ground. I have to attempt to place it on a person or vehicle in order to have the ability to open the ESC menu again. I am still getting the same results, starting the animation with no progress bar.
